### ISSUE TITLE
'NoneType' object has no attribute 'train'

### ISSUE THREAD

**Issue by nguyenthanhhy0108** [lsx0101/Instant-NeRF-Stylization#1]
I met the error 'NoneType' object has no attribute 'train' when I run this command "python tools/run_net.py --config-file ./projects/ngp_stylization/ngp_pair_base.py".

I've already had nvcc 11.5, g++ 10.4 and full requirements.

My GPU is RTX4090.

Please Help me !
Thanks.

![error](https://github.com/user-attachments/assets/b1eecf5a-7c3b-4751-a1d5-9c94f63cb07e)

**Comment by lishaoxu1994** [comment]
Looks like the dataset didn't load successfully
